[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
name = "assignment_tracker"
version = "0.0.2"
description = "A CLI Tool"
packages = ["assignment_tracker_cli"]
install_requires = [
    "rich==13.5.2",
    "typer==0.9.0"
]
